apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qest4za48-nodejs 
  janus-idp.io/tekton: qest4za48-nodejs
  backstage.io/kubernetes-id: qest4za48-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qest4za48-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml