apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qest4za48-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qest4za48-nodejs 
  name: qest4za48-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qest4za48-nodejs 
